### ISSUE TITLE
Is it possible convert the hex string to integer value?

### ISSUE THREAD

**Issue by rolandoo** [drmenguin/minilang-interpreter#1]
Hi, I'm trying to convert the hex string to integer value, is it possible? 

For example: 

def hexstr_to_int(n1 : string) : int{
    //
}
print hexstr_to_int("ABCD");

**Comment by drmenguin** [comment]
Since this is a toy language, I didn't include any constructs which allow you to get part of a string, unfortunately strings are atomic objects which can only be added. In theory it is possible to implement such a function (since the language is Turing Complete) but you'd have to implement strings in a non-atomic way.

**Comment by rolandoo** [comment]
Hmm...I like your resource, it clear and simple, makes me easy understand, but I still cannot understand how to implement, it might be modify the source code? I think it's difficult to me, could you give me some advice step by step? Thanks.

For example:
1. The Lexer : The lexer should add ...
2. The Parser : The parser ...
3. Semantic Analysis: In semantic ...
4. The Interpreter : ...

**Comment by drmenguin** [comment]
Depends, if you want to be able to extract a character from a string, you might want to do something like `my_string[1]` to get the character in position 1. Thus you'd have to modify the Lexer to look out for `[` and `]`, adding a rule to the EBNF and adapting the parser accordingly. Then the changes you make in the semantic analysis and the interpreter will be analogous, where the interpreter will use C++'s [`[]` operator](https://www.cplusplus.com/reference/string/string/operator[]/).

Does this give you a good idea of what to do?

**Comment by rolandoo** [comment]
Great!~I think i can understand what you say. But It sounds difficult in EBNF and semantic analysis. I don't think I am good enough to finish the goal... l will try it. Thanks your advice, drmenguin :)
